version: '3.9'
services:
  #turborepo
  turbo:
    container_name: fullstack
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/app/
       # Just specify a path and let the Engine create a volume
      - /app/node_modules/
    platform: "linux/amd64"
    restart: on-failure

networks:
  turbo-network:
    driver: bridge